name: Wholesale ML CI

on:
  push:
    branches: ["main"]
    paths:
      - "8. Wholesale Customer (Unsupervised)/Production ready/**"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "8. Wholesale Customer (Unsupervised)/Production ready"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sanity check import
        run: |
          python -c "import fastapi, sklearn, numpy, pandas"

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io\
            -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/wholesale-ml:latest .

      - name: Push image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/wholesale-ml:latest